// Autogenerated file (from src/hardware_indep/actions.h.py: via hardware_indep/actions.h.py), do not modify directly.
// Generator: T4P4S (https://github.com/P4ELTE/t4p4s/)

#pragma once

#include "dataplane.h"
#include "common.h"
#include "gen_include.h"

#include "util_packet.h"
#include "stateful_memory_type.h"

#include "ctrl_plane_backend.h"

#include "dpdk_smem.h"

#define FIELD(name, length) uint8_t name[(length + 7) / 8];

typedef enum {
    action_set_nhop,
    action__drop,
    action_NoAction_1,
    action_forward,
    action__drop_1,
    action_NoAction_2,
} actions_e;

typedef struct {
    FIELD(DUMMY_FIELD, 0);
} action_NoAction_1_params_t;

typedef struct {
    FIELD(DUMMY_FIELD, 0);
} action_NoAction_2_params_t;

typedef struct {
    uint32_t nhgroup_1;
} action_set_nhop_params_t;

typedef struct {
    FIELD(DUMMY_FIELD, 0);
} action__drop_params_t;

typedef struct {
    FIELD(DUMMY_FIELD, 0);
} action__drop_1_params_t;

typedef struct {
    uint8_t dmac_val[(48 + 7) / 8];
    uint8_t smac_val[(48 + 7) / 8];
    uint16_t port;
} action_forward_params_t;

typedef union {
    action_set_nhop_params_t set_nhop_params;
    action__drop_params_t _drop_params;
    action_NoAction_1_params_t NoAction_1_params;
} ipv4_lpm_0_action_params_t;

typedef union {
    action_forward_params_t forward_params;
    action__drop_1_params_t _drop_1_params;
    action_NoAction_2_params_t NoAction_2_params;
} nexthops_0_action_params_t;

typedef struct {
    actions_e                     id;
    ipv4_lpm_0_action_params_t params;
} ipv4_lpm_0_action_t;

typedef struct {
    actions_e                     id;
    nexthops_0_action_params_t params;
} nexthops_0_action_t;

void apply_table_ipv4_lpm_0(SHORT_STDPARAMS);
void action_code_set_nhop(action_set_nhop_params_t, SHORT_STDPARAMS);
void action_code__drop(action__drop_params_t, SHORT_STDPARAMS);
void action_code_NoAction_1(action_NoAction_1_params_t, SHORT_STDPARAMS);
void apply_table_nexthops_0(SHORT_STDPARAMS);
void action_code_forward(action_forward_params_t, SHORT_STDPARAMS);
void action_code__drop_1(action__drop_1_params_t, SHORT_STDPARAMS);
void action_code_NoAction_2(action_NoAction_2_params_t, SHORT_STDPARAMS);
typedef struct {
} control_locals_egress_t;

typedef struct {
} control_locals_ingress_t;

typedef struct {
} control_locals_DeparserImpl_t;

typedef struct {
} control_locals_verifyChecksum_t;

typedef struct {
} control_locals_computeChecksum_t;

