// Autogenerated file (from src/hardware_indep/dataplane_table_default_entry.c.py: via hardware_indep/dataplane_table_default_entry.c.py), do not modify directly.
// Generator: T4P4S (https://github.com/P4ELTE/t4p4s/)

#include "gen_include.h"
#include "dataplane_impl.h"

ENTRY(ipv4_lpm_0)* ipv4_lpm_0_get_default_entry(STDPARAMS) {
    return (ENTRY(ipv4_lpm_0)*)tables[TABLE_ipv4_lpm_0][0].default_val;
}

ENTRY(nexthops_0)* nexthops_0_get_default_entry(STDPARAMS) {
    return (ENTRY(nexthops_0)*)tables[TABLE_nexthops_0][0].default_val;
}

