// Autogenerated file (from src/hardware_indep/dpdkx_v1model_log_tuple.c.py: via hardware_indep/dpdkx_v1model_log_tuple.c.py), do not modify directly.
// Generator: T4P4S (https://github.com/P4ELTE/t4p4s/)

#include "common.h"
#include "util_debug.h"

void make_formatter_tuple(char* out_fmt, const char* in_fmt, ...) {
va_list argp;
va_start(argp, in_fmt);

char* param_ptr;
while ((param_ptr = strstr(in_fmt, "{}")) != NULL) {
const char* param_fmt = va_arg(argp, const char*);

int pre_param_len = param_ptr - in_fmt;
int param_len = strlen(param_fmt);

memcpy(out_fmt, in_fmt, pre_param_len);
strcpy(out_fmt + pre_param_len, param_fmt);
out_fmt += pre_param_len + param_len;
in_fmt += pre_param_len + 2; // skip the {} characters
}

// the remaining format characters don't contain {}, copy them
strcpy(out_fmt, in_fmt);

va_end(argp);
}

void print_log_msg_tuple(const char* msg) {
#ifdef T4P4S_DEBUG
debug("    : " T4LIT(Logged,status) ": %s\n", msg);
#else
printf("    : " T4LIT(Logged,status) ": %s\n", msg);
#endif
}

void log_msg__routing_metadata(const char** msg, const routing_metadata_t* parts, SHORT_STDPARAMS) {
    char fmt[1024];
    char text[1024];
    make_formatter_tuple(fmt, *msg, T4LIT(0x%08x,bytes) "=" T4LIT(%d) "/" T4LIT(32) "b");
    sprintf(text, fmt, "parts->nhgroup, parts->nhgroup");
    print_log_msg_tuple(text);
}
void log_msg__headers(const char** msg, const headers_t* parts, SHORT_STDPARAMS) {
    char fmt[1024];
    char text[1024];
    make_formatter_tuple(fmt, *msg, "[""dstAddr="T4LIT(0x%02x%02x%02x%02x%02x%02x,bytes) "/" T4LIT(6) "B"", ""srcAddr="T4LIT(0x%02x%02x%02x%02x%02x%02x,bytes) "/" T4LIT(6) "B"", ""etherType="T4LIT(0x%04x,bytes) "=" T4LIT(%d) "/" T4LIT(16) "b""]", "[""versionIhl="T4LIT(0x%02x,bytes) "=" T4LIT(%d) "/" T4LIT(8) "b"", ""diffserv="T4LIT(0x%02x,bytes) "=" T4LIT(%d) "/" T4LIT(8) "b"", ""totalLen="T4LIT(0x%04x,bytes) "=" T4LIT(%d) "/" T4LIT(16) "b"", ""identification="T4LIT(0x%04x,bytes) "=" T4LIT(%d) "/" T4LIT(16) "b"", ""fragOffset="T4LIT(0x%04x,bytes) "=" T4LIT(%d) "/" T4LIT(16) "b"", ""ttl="T4LIT(0x%02x,bytes) "=" T4LIT(%d) "/" T4LIT(8) "b"", ""protocol="T4LIT(0x%02x,bytes) "=" T4LIT(%d) "/" T4LIT(8) "b"", ""hdrChecksum="T4LIT(0x%04x,bytes) "=" T4LIT(%d) "/" T4LIT(16) "b"", ""srcAddr="T4LIT(0x%08x,bytes) "=" T4LIT(%d) "/" T4LIT(32) "b"", ""dstAddr="T4LIT(0x%08x,bytes) "=" T4LIT(%d) "/" T4LIT(32) "b""]");
    sprintf(text, fmt, "dstAddr=((uint8_t*)parts->ethernet.dstAddr)[0], ((uint8_t*)parts->ethernet.dstAddr)[1], ((uint8_t*)parts->ethernet.dstAddr)[2], ((uint8_t*)parts->ethernet.dstAddr)[3], ((uint8_t*)parts->ethernet.dstAddr)[4], ((uint8_t*)parts->ethernet.dstAddr)[5], srcAddr=((uint8_t*)parts->ethernet.srcAddr)[0], ((uint8_t*)parts->ethernet.srcAddr)[1], ((uint8_t*)parts->ethernet.srcAddr)[2], ((uint8_t*)parts->ethernet.srcAddr)[3], ((uint8_t*)parts->ethernet.srcAddr)[4], ((uint8_t*)parts->ethernet.srcAddr)[5], etherType=parts->ethernet.etherType, parts->ethernet.etherType, versionIhl=parts->ipv4.versionIhl, parts->ipv4.versionIhl, diffserv=parts->ipv4.diffserv, parts->ipv4.diffserv, totalLen=parts->ipv4.totalLen, parts->ipv4.totalLen, identification=parts->ipv4.identification, parts->ipv4.identification, fragOffset=parts->ipv4.fragOffset, parts->ipv4.fragOffset, ttl=parts->ipv4.ttl, parts->ipv4.ttl, protocol=parts->ipv4.protocol, parts->ipv4.protocol, hdrChecksum=parts->ipv4.hdrChecksum, parts->ipv4.hdrChecksum, srcAddr=parts->ipv4.srcAddr, parts->ipv4.srcAddr, dstAddr=parts->ipv4.dstAddr, parts->ipv4.dstAddr");
    print_log_msg_tuple(text);
}
void log_msg__tuple_0(const char** msg, const tuple_0_t* parts, SHORT_STDPARAMS) {
    char fmt[1024];
    char text[1024];
    make_formatter_tuple(fmt, *msg, T4LIT(0x%02x,bytes) "=" T4LIT(%d) "/" T4LIT(8) "b", T4LIT(0x%02x,bytes) "=" T4LIT(%d) "/" T4LIT(8) "b", T4LIT(0x%04x,bytes) "=" T4LIT(%d) "/" T4LIT(16) "b", T4LIT(0x%04x,bytes) "=" T4LIT(%d) "/" T4LIT(16) "b", T4LIT(0x%04x,bytes) "=" T4LIT(%d) "/" T4LIT(16) "b", T4LIT(0x%02x,bytes) "=" T4LIT(%d) "/" T4LIT(8) "b", T4LIT(0x%02x,bytes) "=" T4LIT(%d) "/" T4LIT(8) "b", T4LIT(0x%08x,bytes) "=" T4LIT(%d) "/" T4LIT(32) "b", T4LIT(0x%08x,bytes) "=" T4LIT(%d) "/" T4LIT(32) "b");
    sprintf(text, fmt, "parts->f0, parts->f0, parts->f1, parts->f1, parts->f2, parts->f2, parts->f3, parts->f3, parts->f4, parts->f4, parts->f5, parts->f5, parts->f6, parts->f6, parts->f7, parts->f7, parts->f8, parts->f8");
    print_log_msg_tuple(text);
}
