// Autogenerated file (from src/hardware_indep/multi_actions.c.py: via hardware_indep/multi_actions.c.py), do not modify directly.
// Generator: T4P4S (https://github.com/P4ELTE/t4p4s/)

#include <unistd.h>

#include "dpdk_lib.h"
#include "actions.h"
#include "util_debug.h"
#include "util_packet.h"

#include "dpdk_primitives.h"
#include "dpdkx_gen_extern.h"

extern const char* action_names[];
extern const char* action_canonical_names[];
extern const char* action_short_names[];

extern void check_hdr_valid(packet_descriptor_t* pd, field_instance_e fld, const char* unspec);

extern ctrl_plane_backend bg;

extern void do_assignment(header_instance_e dst_hdr, header_instance_e src_hdr, SHORT_STDPARAMS);

#if T4P4S_MULTI_IDX == 0
    // action name: ingress.drop; ingress.drop
    void action_code_drop(action_drop_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: ingress.drop; ingress.drop
    void action_code_drop_1(action_drop_1_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: ingress.drop; ingress.drop
    void action_code_drop_2(action_drop_2_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: ingress.drop; ingress.drop
    void action_code_drop_3(action_drop_3_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: ingress.drop; ingress.drop
    void action_code_drop_4(action_drop_4_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: ingress.drop; ingress.drop
    void action_code_drop_5(action_drop_5_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: ingress.drop; ingress.drop
    void action_code_drop_6(action_drop_6_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: ingress.drop; ingress.drop
    void action_code_drop_7(action_drop_7_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: ingress.drop; ingress.drop
    void action_code_drop_8(action_drop_8_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: ingress.drop; ingress.drop
    void action_code_drop_9(action_drop_9_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act)
    void action_code_act(action_act_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_0)
    void action_code_act_0(action_act_0_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp = false;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall212)
    void action_code_firewall212(action_firewall212_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_0 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_1)
    void action_code_act_1(action_act_1_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_1 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_2)
    void action_code_act_2(action_act_2_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_1 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall212_0)
    void action_code_firewall212_0(action_firewall212_0_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_0 = local_vars->tmp_1;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall212_1)
    void action_code_firewall212_1(action_firewall212_1_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_2 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_3)
    void action_code_act_3(action_act_3_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_3 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_4)
    void action_code_act_4(action_act_4_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_3 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall212_2)
    void action_code_firewall212_2(action_firewall212_2_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_2 = local_vars->tmp_3;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall213)
    void action_code_firewall213(action_firewall213_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 uint8_t const8__01 = 1;
 uint8_t const8__01_3 = 1;
uint8_t assignment_0002 = (uint8_t)((const8__01_3)); // dbg False False True Constant->PathExpression
memcpy(&(local_vars->dropped_0), &assignment_0002 /* dbg False False True Constant->PathExpression */, 1);
dbg_bytes(&(local_vars->dropped_0), 1, "    : Set " T4LIT(dropped_0,field) "/" T4LIT(1B) " = " T4LIT(1) " = ");
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_5)
    void action_code_act_5(action_act_5_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_4 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_6)
    void action_code_act_6(action_act_6_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_4 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall215)
    void action_code_firewall215(action_firewall215_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_5 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_7)
    void action_code_act_7(action_act_7_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_6 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_8)
    void action_code_act_8(action_act_8_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_6 = false;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall215_0)
    void action_code_firewall215_0(action_firewall215_0_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_5 = local_vars->tmp_6;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall215_1)
    void action_code_firewall215_1(action_firewall215_1_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_7 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_9)
    void action_code_act_9(action_act_9_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_8 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_10)
    void action_code_act_10(action_act_10_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_8 = false;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall215_2)
    void action_code_firewall215_2(action_firewall215_2_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_7 = local_vars->tmp_8;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall216)
    void action_code_firewall216(action_firewall216_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 uint8_t const8__01_4 = 1;
 uint8_t const8__01_6 = 1;
uint8_t assignment_0005 = (uint8_t)((const8__01_6)); // dbg False False True Constant->PathExpression
memcpy(&(local_vars->dropped_0), &assignment_0005 /* dbg False False True Constant->PathExpression */, 1);
dbg_bytes(&(local_vars->dropped_0), 1, "    : Set " T4LIT(dropped_0,field) "/" T4LIT(1B) " = " T4LIT(1) " = ");
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_11)
    void action_code_act_11(action_act_11_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_9 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_12)
    void action_code_act_12(action_act_12_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_9 = false;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall218)
    void action_code_firewall218(action_firewall218_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_10 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_13)
    void action_code_act_13(action_act_13_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_11 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_14)
    void action_code_act_14(action_act_14_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_11 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall218_0)
    void action_code_firewall218_0(action_firewall218_0_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_10 = local_vars->tmp_11;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall219)
    void action_code_firewall219(action_firewall219_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 uint8_t const8__01_7 = 1;
 uint8_t const8__01_9 = 1;
uint8_t assignment_0008 = (uint8_t)((const8__01_9)); // dbg False False True Constant->PathExpression
memcpy(&(local_vars->dropped_0), &assignment_0008 /* dbg False False True Constant->PathExpression */, 1);
dbg_bytes(&(local_vars->dropped_0), 1, "    : Set " T4LIT(dropped_0,field) "/" T4LIT(1B) " = " T4LIT(1) " = ");
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_15)
    void action_code_act_15(action_act_15_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_12 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_16)
    void action_code_act_16(action_act_16_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_12 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_17)
    void action_code_act_17(action_act_17_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_14 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_18)
    void action_code_act_18(action_act_18_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_14 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall222)
    void action_code_firewall222(action_firewall222_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_13 = local_vars->tmp_14;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall222_0)
    void action_code_firewall222_0(action_firewall222_0_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_13 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall223)
    void action_code_firewall223(action_firewall223_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 uint8_t const8__01_10 = 1;
 uint8_t const8__01_12 = 1;
uint8_t assignment_0011 = (uint8_t)((const8__01_12)); // dbg False False True Constant->PathExpression
memcpy(&(local_vars->dropped_0), &assignment_0011 /* dbg False False True Constant->PathExpression */, 1);
dbg_bytes(&(local_vars->dropped_0), 1, "    : Set " T4LIT(dropped_0,field) "/" T4LIT(1B) " = " T4LIT(1) " = ");
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall229)
    void action_code_firewall229(action_firewall229_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 check_hdr_valid(pd, FLD(all_metadatas,egress_port), "0x14f /* pseudorandom 9 bit value */");
 check_hdr_valid(pd, FLD(all_metadatas,egress_port), "0x14f /* pseudorandom 9 bit value */");
 uint16_t bitmask_9b_0013 = 0x1ff;
 uint16_t casting_0015 = (uint16_t)((((uint16_t)GET32_def(src_pkt(pd), FLD(all_metadatas,egress_port), 0x14f /* pseudorandom 9 bit value */)) + 1));
 uint16_t masking_0014 = (uint16_t)(casting_0015);
set_fld(pd, FLD(all_metadatas,egress_port), (((bitmask_9b_0013 & masking_0014)) & (1)));
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall210)
    void action_code_firewall210(action_firewall210_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 uint8_t const8__00 = 0;
 uint8_t const8__00_18 = 0;
uint8_t assignment_0017 = (uint8_t)((const8__00_18)); // dbg False False True Constant->PathExpression
memcpy(&(local_vars->dropped_0), &assignment_0017 /* dbg False False True Constant->PathExpression */, 1);
dbg_bytes(&(local_vars->dropped_0), 1, "    : Set " T4LIT(dropped_0,field) "/" T4LIT(1B) " = " T4LIT(0) " = ");
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: ingress.drop; ingress.drop
    void action_code_drop(action_drop_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: ingress.drop; ingress.drop
    void action_code_drop_1(action_drop_1_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: ingress.drop; ingress.drop
    void action_code_drop_2(action_drop_2_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: ingress.drop; ingress.drop
    void action_code_drop_3(action_drop_3_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: ingress.drop; ingress.drop
    void action_code_drop_4(action_drop_4_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: ingress.drop; ingress.drop
    void action_code_drop_5(action_drop_5_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: ingress.drop; ingress.drop
    void action_code_drop_6(action_drop_6_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: ingress.drop; ingress.drop
    void action_code_drop_7(action_drop_7_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: ingress.drop; ingress.drop
    void action_code_drop_8(action_drop_8_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: ingress.drop; ingress.drop
    void action_code_drop_9(action_drop_9_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act)
    void action_code_act(action_act_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_0)
    void action_code_act_0(action_act_0_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp = false;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall212)
    void action_code_firewall212(action_firewall212_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_0 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_1)
    void action_code_act_1(action_act_1_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_1 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_2)
    void action_code_act_2(action_act_2_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_1 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall212_0)
    void action_code_firewall212_0(action_firewall212_0_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_0 = local_vars->tmp_1;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall212_1)
    void action_code_firewall212_1(action_firewall212_1_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_2 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_3)
    void action_code_act_3(action_act_3_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_3 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_4)
    void action_code_act_4(action_act_4_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_3 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall212_2)
    void action_code_firewall212_2(action_firewall212_2_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_2 = local_vars->tmp_3;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall213)
    void action_code_firewall213(action_firewall213_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 uint8_t const8__01_19 = 1;
 uint8_t const8__01_21 = 1;
uint8_t assignment_0020 = (uint8_t)((const8__01_21)); // dbg False False True Constant->PathExpression
memcpy(&(local_vars->dropped_0), &assignment_0020 /* dbg False False True Constant->PathExpression */, 1);
dbg_bytes(&(local_vars->dropped_0), 1, "    : Set " T4LIT(dropped_0,field) "/" T4LIT(1B) " = " T4LIT(1) " = ");
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_5)
    void action_code_act_5(action_act_5_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_4 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_6)
    void action_code_act_6(action_act_6_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_4 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall215)
    void action_code_firewall215(action_firewall215_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_5 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_7)
    void action_code_act_7(action_act_7_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_6 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_8)
    void action_code_act_8(action_act_8_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_6 = false;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall215_0)
    void action_code_firewall215_0(action_firewall215_0_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_5 = local_vars->tmp_6;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall215_1)
    void action_code_firewall215_1(action_firewall215_1_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_7 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_9)
    void action_code_act_9(action_act_9_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_8 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_10)
    void action_code_act_10(action_act_10_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_8 = false;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall215_2)
    void action_code_firewall215_2(action_firewall215_2_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_7 = local_vars->tmp_8;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall216)
    void action_code_firewall216(action_firewall216_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 uint8_t const8__01_22 = 1;
 uint8_t const8__01_24 = 1;
uint8_t assignment_0023 = (uint8_t)((const8__01_24)); // dbg False False True Constant->PathExpression
memcpy(&(local_vars->dropped_0), &assignment_0023 /* dbg False False True Constant->PathExpression */, 1);
dbg_bytes(&(local_vars->dropped_0), 1, "    : Set " T4LIT(dropped_0,field) "/" T4LIT(1B) " = " T4LIT(1) " = ");
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_11)
    void action_code_act_11(action_act_11_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_9 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_12)
    void action_code_act_12(action_act_12_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_9 = false;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall218)
    void action_code_firewall218(action_firewall218_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_10 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_13)
    void action_code_act_13(action_act_13_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_11 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_14)
    void action_code_act_14(action_act_14_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_11 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall218_0)
    void action_code_firewall218_0(action_firewall218_0_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_10 = local_vars->tmp_11;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall219)
    void action_code_firewall219(action_firewall219_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 uint8_t const8__01_25 = 1;
 uint8_t const8__01_27 = 1;
uint8_t assignment_0026 = (uint8_t)((const8__01_27)); // dbg False False True Constant->PathExpression
memcpy(&(local_vars->dropped_0), &assignment_0026 /* dbg False False True Constant->PathExpression */, 1);
dbg_bytes(&(local_vars->dropped_0), 1, "    : Set " T4LIT(dropped_0,field) "/" T4LIT(1B) " = " T4LIT(1) " = ");
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_15)
    void action_code_act_15(action_act_15_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_12 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_16)
    void action_code_act_16(action_act_16_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_12 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_17)
    void action_code_act_17(action_act_17_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_14 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_18)
    void action_code_act_18(action_act_18_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_14 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall222)
    void action_code_firewall222(action_firewall222_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_13 = local_vars->tmp_14;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall222_0)
    void action_code_firewall222_0(action_firewall222_0_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_13 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall223)
    void action_code_firewall223(action_firewall223_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 uint8_t const8__01_28 = 1;
 uint8_t const8__01_30 = 1;
uint8_t assignment_0029 = (uint8_t)((const8__01_30)); // dbg False False True Constant->PathExpression
memcpy(&(local_vars->dropped_0), &assignment_0029 /* dbg False False True Constant->PathExpression */, 1);
dbg_bytes(&(local_vars->dropped_0), 1, "    : Set " T4LIT(dropped_0,field) "/" T4LIT(1B) " = " T4LIT(1) " = ");
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall229)
    void action_code_firewall229(action_firewall229_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 check_hdr_valid(pd, FLD(all_metadatas,egress_port), "0x14f /* pseudorandom 9 bit value */");
 check_hdr_valid(pd, FLD(all_metadatas,egress_port), "0x14f /* pseudorandom 9 bit value */");
 uint16_t bitmask_9b_0031 = 0x1ff;
 uint16_t casting_0033 = (uint16_t)((((uint16_t)GET32_def(src_pkt(pd), FLD(all_metadatas,egress_port), 0x14f /* pseudorandom 9 bit value */)) + 1));
 uint16_t masking_0032 = (uint16_t)(casting_0033);
set_fld(pd, FLD(all_metadatas,egress_port), (((bitmask_9b_0031 & masking_0032)) & (1)));
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall210)
    void action_code_firewall210(action_firewall210_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 uint8_t const8__00_34 = 0;
 uint8_t const8__00_36 = 0;
uint8_t assignment_0035 = (uint8_t)((const8__00_36)); // dbg False False True Constant->PathExpression
memcpy(&(local_vars->dropped_0), &assignment_0035 /* dbg False False True Constant->PathExpression */, 1);
dbg_bytes(&(local_vars->dropped_0), 1, "    : Set " T4LIT(dropped_0,field) "/" T4LIT(1B) " = " T4LIT(0) " = ");
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: ingress.drop; ingress.drop
    void action_code_drop(action_drop_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: ingress.drop; ingress.drop
    void action_code_drop_1(action_drop_1_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: ingress.drop; ingress.drop
    void action_code_drop_2(action_drop_2_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: ingress.drop; ingress.drop
    void action_code_drop_3(action_drop_3_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: ingress.drop; ingress.drop
    void action_code_drop_4(action_drop_4_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: ingress.drop; ingress.drop
    void action_code_drop_5(action_drop_5_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: ingress.drop; ingress.drop
    void action_code_drop_6(action_drop_6_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: ingress.drop; ingress.drop
    void action_code_drop_7(action_drop_7_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: ingress.drop; ingress.drop
    void action_code_drop_8(action_drop_8_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: ingress.drop; ingress.drop
    void action_code_drop_9(action_drop_9_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act)
    void action_code_act(action_act_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_0)
    void action_code_act_0(action_act_0_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp = false;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall212)
    void action_code_firewall212(action_firewall212_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_0 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_1)
    void action_code_act_1(action_act_1_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_1 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_2)
    void action_code_act_2(action_act_2_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_1 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall212_0)
    void action_code_firewall212_0(action_firewall212_0_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_0 = local_vars->tmp_1;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall212_1)
    void action_code_firewall212_1(action_firewall212_1_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_2 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_3)
    void action_code_act_3(action_act_3_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_3 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_4)
    void action_code_act_4(action_act_4_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_3 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall212_2)
    void action_code_firewall212_2(action_firewall212_2_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_2 = local_vars->tmp_3;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall213)
    void action_code_firewall213(action_firewall213_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 uint8_t const8__01_37 = 1;
 uint8_t const8__01_39 = 1;
uint8_t assignment_0038 = (uint8_t)((const8__01_39)); // dbg False False True Constant->PathExpression
memcpy(&(local_vars->dropped_0), &assignment_0038 /* dbg False False True Constant->PathExpression */, 1);
dbg_bytes(&(local_vars->dropped_0), 1, "    : Set " T4LIT(dropped_0,field) "/" T4LIT(1B) " = " T4LIT(1) " = ");
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_5)
    void action_code_act_5(action_act_5_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_4 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_6)
    void action_code_act_6(action_act_6_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_4 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall215)
    void action_code_firewall215(action_firewall215_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_5 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_7)
    void action_code_act_7(action_act_7_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_6 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_8)
    void action_code_act_8(action_act_8_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_6 = false;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall215_0)
    void action_code_firewall215_0(action_firewall215_0_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_5 = local_vars->tmp_6;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall215_1)
    void action_code_firewall215_1(action_firewall215_1_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_7 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_9)
    void action_code_act_9(action_act_9_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_8 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_10)
    void action_code_act_10(action_act_10_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_8 = false;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall215_2)
    void action_code_firewall215_2(action_firewall215_2_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_7 = local_vars->tmp_8;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall216)
    void action_code_firewall216(action_firewall216_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 uint8_t const8__01_40 = 1;
 uint8_t const8__01_42 = 1;
uint8_t assignment_0041 = (uint8_t)((const8__01_42)); // dbg False False True Constant->PathExpression
memcpy(&(local_vars->dropped_0), &assignment_0041 /* dbg False False True Constant->PathExpression */, 1);
dbg_bytes(&(local_vars->dropped_0), 1, "    : Set " T4LIT(dropped_0,field) "/" T4LIT(1B) " = " T4LIT(1) " = ");
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_11)
    void action_code_act_11(action_act_11_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_9 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_12)
    void action_code_act_12(action_act_12_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_9 = false;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall218)
    void action_code_firewall218(action_firewall218_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_10 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_13)
    void action_code_act_13(action_act_13_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_11 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_14)
    void action_code_act_14(action_act_14_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_11 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall218_0)
    void action_code_firewall218_0(action_firewall218_0_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_10 = local_vars->tmp_11;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall219)
    void action_code_firewall219(action_firewall219_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 uint8_t const8__01_43 = 1;
 uint8_t const8__01_45 = 1;
uint8_t assignment_0044 = (uint8_t)((const8__01_45)); // dbg False False True Constant->PathExpression
memcpy(&(local_vars->dropped_0), &assignment_0044 /* dbg False False True Constant->PathExpression */, 1);
dbg_bytes(&(local_vars->dropped_0), 1, "    : Set " T4LIT(dropped_0,field) "/" T4LIT(1B) " = " T4LIT(1) " = ");
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_15)
    void action_code_act_15(action_act_15_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_12 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_16)
    void action_code_act_16(action_act_16_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_12 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_17)
    void action_code_act_17(action_act_17_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_14 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_18)
    void action_code_act_18(action_act_18_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_14 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall222)
    void action_code_firewall222(action_firewall222_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_13 = local_vars->tmp_14;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall222_0)
    void action_code_firewall222_0(action_firewall222_0_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_13 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall223)
    void action_code_firewall223(action_firewall223_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 uint8_t const8__01_46 = 1;
 uint8_t const8__01_48 = 1;
uint8_t assignment_0047 = (uint8_t)((const8__01_48)); // dbg False False True Constant->PathExpression
memcpy(&(local_vars->dropped_0), &assignment_0047 /* dbg False False True Constant->PathExpression */, 1);
dbg_bytes(&(local_vars->dropped_0), 1, "    : Set " T4LIT(dropped_0,field) "/" T4LIT(1B) " = " T4LIT(1) " = ");
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall229)
    void action_code_firewall229(action_firewall229_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 check_hdr_valid(pd, FLD(all_metadatas,egress_port), "0x14f /* pseudorandom 9 bit value */");
 check_hdr_valid(pd, FLD(all_metadatas,egress_port), "0x14f /* pseudorandom 9 bit value */");
 uint16_t bitmask_9b_0049 = 0x1ff;
 uint16_t casting_0051 = (uint16_t)((((uint16_t)GET32_def(src_pkt(pd), FLD(all_metadatas,egress_port), 0x14f /* pseudorandom 9 bit value */)) + 1));
 uint16_t masking_0050 = (uint16_t)(casting_0051);
set_fld(pd, FLD(all_metadatas,egress_port), (((bitmask_9b_0049 & masking_0050)) & (1)));
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall210)
    void action_code_firewall210(action_firewall210_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 uint8_t const8__00_52 = 0;
 uint8_t const8__00_54 = 0;
uint8_t assignment_0053 = (uint8_t)((const8__00_54)); // dbg False False True Constant->PathExpression
memcpy(&(local_vars->dropped_0), &assignment_0053 /* dbg False False True Constant->PathExpression */, 1);
dbg_bytes(&(local_vars->dropped_0), 1, "    : Set " T4LIT(dropped_0,field) "/" T4LIT(1B) " = " T4LIT(0) " = ");
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: ingress.drop; ingress.drop
    void action_code_drop(action_drop_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: ingress.drop; ingress.drop
    void action_code_drop_1(action_drop_1_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: ingress.drop; ingress.drop
    void action_code_drop_2(action_drop_2_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: ingress.drop; ingress.drop
    void action_code_drop_3(action_drop_3_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: ingress.drop; ingress.drop
    void action_code_drop_4(action_drop_4_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: ingress.drop; ingress.drop
    void action_code_drop_5(action_drop_5_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: ingress.drop; ingress.drop
    void action_code_drop_6(action_drop_6_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: ingress.drop; ingress.drop
    void action_code_drop_7(action_drop_7_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: ingress.drop; ingress.drop
    void action_code_drop_8(action_drop_8_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: ingress.drop; ingress.drop
    void action_code_drop_9(action_drop_9_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act)
    void action_code_act(action_act_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_0)
    void action_code_act_0(action_act_0_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp = false;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall212)
    void action_code_firewall212(action_firewall212_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_0 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_1)
    void action_code_act_1(action_act_1_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_1 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_2)
    void action_code_act_2(action_act_2_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_1 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall212_0)
    void action_code_firewall212_0(action_firewall212_0_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_0 = local_vars->tmp_1;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall212_1)
    void action_code_firewall212_1(action_firewall212_1_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_2 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_3)
    void action_code_act_3(action_act_3_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_3 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_4)
    void action_code_act_4(action_act_4_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_3 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall212_2)
    void action_code_firewall212_2(action_firewall212_2_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_2 = local_vars->tmp_3;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall213)
    void action_code_firewall213(action_firewall213_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 uint8_t const8__01_55 = 1;
 uint8_t const8__01_57 = 1;
uint8_t assignment_0056 = (uint8_t)((const8__01_57)); // dbg False False True Constant->PathExpression
memcpy(&(local_vars->dropped_0), &assignment_0056 /* dbg False False True Constant->PathExpression */, 1);
dbg_bytes(&(local_vars->dropped_0), 1, "    : Set " T4LIT(dropped_0,field) "/" T4LIT(1B) " = " T4LIT(1) " = ");
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_5)
    void action_code_act_5(action_act_5_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_4 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_6)
    void action_code_act_6(action_act_6_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_4 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall215)
    void action_code_firewall215(action_firewall215_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_5 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_7)
    void action_code_act_7(action_act_7_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_6 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_8)
    void action_code_act_8(action_act_8_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_6 = false;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall215_0)
    void action_code_firewall215_0(action_firewall215_0_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_5 = local_vars->tmp_6;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall215_1)
    void action_code_firewall215_1(action_firewall215_1_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_7 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_9)
    void action_code_act_9(action_act_9_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_8 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_10)
    void action_code_act_10(action_act_10_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_8 = false;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall215_2)
    void action_code_firewall215_2(action_firewall215_2_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_7 = local_vars->tmp_8;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall216)
    void action_code_firewall216(action_firewall216_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 uint8_t const8__01_58 = 1;
 uint8_t const8__01_60 = 1;
uint8_t assignment_0059 = (uint8_t)((const8__01_60)); // dbg False False True Constant->PathExpression
memcpy(&(local_vars->dropped_0), &assignment_0059 /* dbg False False True Constant->PathExpression */, 1);
dbg_bytes(&(local_vars->dropped_0), 1, "    : Set " T4LIT(dropped_0,field) "/" T4LIT(1B) " = " T4LIT(1) " = ");
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_11)
    void action_code_act_11(action_act_11_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_9 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_12)
    void action_code_act_12(action_act_12_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_9 = false;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall218)
    void action_code_firewall218(action_firewall218_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_10 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_13)
    void action_code_act_13(action_act_13_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_11 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_14)
    void action_code_act_14(action_act_14_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_11 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall218_0)
    void action_code_firewall218_0(action_firewall218_0_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_10 = local_vars->tmp_11;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall219)
    void action_code_firewall219(action_firewall219_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 uint8_t const8__01_61 = 1;
 uint8_t const8__01_63 = 1;
uint8_t assignment_0062 = (uint8_t)((const8__01_63)); // dbg False False True Constant->PathExpression
memcpy(&(local_vars->dropped_0), &assignment_0062 /* dbg False False True Constant->PathExpression */, 1);
dbg_bytes(&(local_vars->dropped_0), 1, "    : Set " T4LIT(dropped_0,field) "/" T4LIT(1B) " = " T4LIT(1) " = ");
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_15)
    void action_code_act_15(action_act_15_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_12 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_16)
    void action_code_act_16(action_act_16_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_12 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_17)
    void action_code_act_17(action_act_17_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_14 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_18)
    void action_code_act_18(action_act_18_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_14 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall222)
    void action_code_firewall222(action_firewall222_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_13 = local_vars->tmp_14;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall222_0)
    void action_code_firewall222_0(action_firewall222_0_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_13 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall223)
    void action_code_firewall223(action_firewall223_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 uint8_t const8__01_64 = 1;
 uint8_t const8__01_66 = 1;
uint8_t assignment_0065 = (uint8_t)((const8__01_66)); // dbg False False True Constant->PathExpression
memcpy(&(local_vars->dropped_0), &assignment_0065 /* dbg False False True Constant->PathExpression */, 1);
dbg_bytes(&(local_vars->dropped_0), 1, "    : Set " T4LIT(dropped_0,field) "/" T4LIT(1B) " = " T4LIT(1) " = ");
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall229)
    void action_code_firewall229(action_firewall229_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 check_hdr_valid(pd, FLD(all_metadatas,egress_port), "0x14f /* pseudorandom 9 bit value */");
 check_hdr_valid(pd, FLD(all_metadatas,egress_port), "0x14f /* pseudorandom 9 bit value */");
 uint16_t bitmask_9b_0067 = 0x1ff;
 uint16_t casting_0069 = (uint16_t)((((uint16_t)GET32_def(src_pkt(pd), FLD(all_metadatas,egress_port), 0x14f /* pseudorandom 9 bit value */)) + 1));
 uint16_t masking_0068 = (uint16_t)(casting_0069);
set_fld(pd, FLD(all_metadatas,egress_port), (((bitmask_9b_0067 & masking_0068)) & (1)));
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall210)
    void action_code_firewall210(action_firewall210_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 uint8_t const8__00_70 = 0;
 uint8_t const8__00_72 = 0;
uint8_t assignment_0071 = (uint8_t)((const8__00_72)); // dbg False False True Constant->PathExpression
memcpy(&(local_vars->dropped_0), &assignment_0071 /* dbg False False True Constant->PathExpression */, 1);
dbg_bytes(&(local_vars->dropped_0), 1, "    : Set " T4LIT(dropped_0,field) "/" T4LIT(1B) " = " T4LIT(0) " = ");
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: ingress.drop; ingress.drop
    void action_code_drop(action_drop_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: ingress.drop; ingress.drop
    void action_code_drop_1(action_drop_1_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: ingress.drop; ingress.drop
    void action_code_drop_2(action_drop_2_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: ingress.drop; ingress.drop
    void action_code_drop_3(action_drop_3_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: ingress.drop; ingress.drop
    void action_code_drop_4(action_drop_4_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: ingress.drop; ingress.drop
    void action_code_drop_5(action_drop_5_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: ingress.drop; ingress.drop
    void action_code_drop_6(action_drop_6_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: ingress.drop; ingress.drop
    void action_code_drop_7(action_drop_7_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: ingress.drop; ingress.drop
    void action_code_drop_8(action_drop_8_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: ingress.drop; ingress.drop
    void action_code_drop_9(action_drop_9_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
SHORT_EXTERNCALL0(mark_to_drop)(SHORT_STDPARAMS_IN);
;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act)
    void action_code_act(action_act_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_0)
    void action_code_act_0(action_act_0_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp = false;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall212)
    void action_code_firewall212(action_firewall212_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_0 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_1)
    void action_code_act_1(action_act_1_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_1 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_2)
    void action_code_act_2(action_act_2_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_1 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall212_0)
    void action_code_firewall212_0(action_firewall212_0_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_0 = local_vars->tmp_1;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall212_1)
    void action_code_firewall212_1(action_firewall212_1_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_2 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_3)
    void action_code_act_3(action_act_3_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_3 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_4)
    void action_code_act_4(action_act_4_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_3 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall212_2)
    void action_code_firewall212_2(action_firewall212_2_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_2 = local_vars->tmp_3;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall213)
    void action_code_firewall213(action_firewall213_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 uint8_t const8__01_73 = 1;
 uint8_t const8__01_75 = 1;
uint8_t assignment_0074 = (uint8_t)((const8__01_75)); // dbg False False True Constant->PathExpression
memcpy(&(local_vars->dropped_0), &assignment_0074 /* dbg False False True Constant->PathExpression */, 1);
dbg_bytes(&(local_vars->dropped_0), 1, "    : Set " T4LIT(dropped_0,field) "/" T4LIT(1B) " = " T4LIT(1) " = ");
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_5)
    void action_code_act_5(action_act_5_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_4 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_6)
    void action_code_act_6(action_act_6_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_4 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall215)
    void action_code_firewall215(action_firewall215_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_5 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_7)
    void action_code_act_7(action_act_7_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_6 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_8)
    void action_code_act_8(action_act_8_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_6 = false;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall215_0)
    void action_code_firewall215_0(action_firewall215_0_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_5 = local_vars->tmp_6;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall215_1)
    void action_code_firewall215_1(action_firewall215_1_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_7 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_9)
    void action_code_act_9(action_act_9_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_8 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_10)
    void action_code_act_10(action_act_10_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_8 = false;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall215_2)
    void action_code_firewall215_2(action_firewall215_2_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_7 = local_vars->tmp_8;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall216)
    void action_code_firewall216(action_firewall216_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 uint8_t const8__01_76 = 1;
 uint8_t const8__01_78 = 1;
uint8_t assignment_0077 = (uint8_t)((const8__01_78)); // dbg False False True Constant->PathExpression
memcpy(&(local_vars->dropped_0), &assignment_0077 /* dbg False False True Constant->PathExpression */, 1);
dbg_bytes(&(local_vars->dropped_0), 1, "    : Set " T4LIT(dropped_0,field) "/" T4LIT(1B) " = " T4LIT(1) " = ");
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_11)
    void action_code_act_11(action_act_11_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_9 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_12)
    void action_code_act_12(action_act_12_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_9 = false;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall218)
    void action_code_firewall218(action_firewall218_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_10 = true;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_13)
    void action_code_act_13(action_act_13_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_11 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_14)
    void action_code_act_14(action_act_14_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_11 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall218_0)
    void action_code_firewall218_0(action_firewall218_0_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_10 = local_vars->tmp_11;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall219)
    void action_code_firewall219(action_firewall219_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 uint8_t const8__01_79 = 1;
 uint8_t const8__01_81 = 1;
uint8_t assignment_0080 = (uint8_t)((const8__01_81)); // dbg False False True Constant->PathExpression
memcpy(&(local_vars->dropped_0), &assignment_0080 /* dbg False False True Constant->PathExpression */, 1);
dbg_bytes(&(local_vars->dropped_0), 1, "    : Set " T4LIT(dropped_0,field) "/" T4LIT(1B) " = " T4LIT(1) " = ");
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_15)
    void action_code_act_15(action_act_15_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_12 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_16)
    void action_code_act_16(action_act_16_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_12 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (act_17)
    void action_code_act_17(action_act_17_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_14 = true;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (act_18)
    void action_code_act_18(action_act_18_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_14 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall222)
    void action_code_firewall222(action_firewall222_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_13 = local_vars->tmp_14;
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall222_0)
    void action_code_firewall222_0(action_firewall222_0_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;
local_vars->tmp_13 = false;
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall223)
    void action_code_firewall223(action_firewall223_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 uint8_t const8__01_82 = 1;
 uint8_t const8__01_84 = 1;
uint8_t assignment_0083 = (uint8_t)((const8__01_84)); // dbg False False True Constant->PathExpression
memcpy(&(local_vars->dropped_0), &assignment_0083 /* dbg False False True Constant->PathExpression */, 1);
dbg_bytes(&(local_vars->dropped_0), 1, "    : Set " T4LIT(dropped_0,field) "/" T4LIT(1B) " = " T4LIT(1) " = ");
    }
#endif // T4P4S_MULTI_IDX == 1

#if T4P4S_MULTI_IDX == 0
    // action name: (firewall229)
    void action_code_firewall229(action_firewall229_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 check_hdr_valid(pd, FLD(all_metadatas,egress_port), "0x14f /* pseudorandom 9 bit value */");
 check_hdr_valid(pd, FLD(all_metadatas,egress_port), "0x14f /* pseudorandom 9 bit value */");
 uint16_t bitmask_9b_0085 = 0x1ff;
 uint16_t casting_0087 = (uint16_t)((((uint16_t)GET32_def(src_pkt(pd), FLD(all_metadatas,egress_port), 0x14f /* pseudorandom 9 bit value */)) + 1));
 uint16_t masking_0086 = (uint16_t)(casting_0087);
set_fld(pd, FLD(all_metadatas,egress_port), (((bitmask_9b_0085 & masking_0086)) & (1)));
    }
#endif // T4P4S_MULTI_IDX == 0

#if T4P4S_MULTI_IDX == 1
    // action name: (firewall210)
    void action_code_firewall210(action_firewall210_params_t parameters, SHORT_STDPARAMS) {
        control_locals_1_ingress_t* local_vars = (control_locals_1_ingress_t*) pd->control_locals;

 uint8_t const8__00_88 = 0;
 uint8_t const8__00_90 = 0;
uint8_t assignment_0089 = (uint8_t)((const8__00_90)); // dbg False False True Constant->PathExpression
memcpy(&(local_vars->dropped_0), &assignment_0089 /* dbg False False True Constant->PathExpression */, 1);
dbg_bytes(&(local_vars->dropped_0), 1, "    : Set " T4LIT(dropped_0,field) "/" T4LIT(1B) " = " T4LIT(0) " = ");
    }
#endif // T4P4S_MULTI_IDX == 1

