// Autogenerated file (from src/hardware_indep/parser_stages.h.py: via hardware_indep/parser_stages.h.py), do not modify directly.
// Generator: T4P4S (https://github.com/P4ELTE/t4p4s/)

#pragma once

#include "dpdk_lib.h"
#include "util_packet.h"

int parser_extract_ethernet(int vwlen, STDPARAMS);
int parser_extract_udp(int vwlen, STDPARAMS);
int parser_extract_arp(int vwlen, STDPARAMS);
int parser_extract_icmp(int vwlen, STDPARAMS);
int parser_extract_ipv4(int vwlen, STDPARAMS);
int parser_extract_tcp(int vwlen, STDPARAMS);
void cannot_parse_hdr(const char* varwidth_txt, const char* hdr_name, int hdrlen, int vwlen, STDPARAMS);
