// Autogenerated file (from src/hardware_indep/stats_requirements.c.py: via hardware_indep/stats_requirements.c.py), do not modify directly.
// Generator: T4P4S (https://github.com/P4ELTE/t4p4s/)

// SPDX-License-Identifier: Apache-2.0
// Copyright 2021 Eotvos Lorand University, Budapest, Hungary

#include <string.h>

#include "common.h"
#include "dpdk_lib.h"

#ifndef T4P4S_STATS
    #else
    
    extern t4p4s_stats_t t4p4s_stats_per_packet;
    
    
    typedef enum {
        reqcond_apply,
        reqcond_hit,
        reqcond_miss,
        reqcond_cond,
        reqcond_run,
        reqcond_parse,
        reqcond_NONE,
        reqcond_ERROR,
    } reqcond_e;
    
    
    reqcond_e get_reqcond(const char* name) {
        if (!strcmp("apply", name))    return reqcond_apply;
        if (!strcmp("hit", name))    return reqcond_hit;
        if (!strcmp("miss", name))    return reqcond_miss;
        if (!strcmp("cond", name))    return reqcond_cond;
        if (!strcmp("run", name))    return reqcond_run;
        if (!strcmp("parse", name))    return reqcond_parse;
        if (!strcmp("NONE", name))    return reqcond_NONE;
        if (!strcmp("ERROR", name))    return reqcond_ERROR;
        return reqcond_ERROR;
    };
    
    
    const char* get_reqcond_txt(reqcond_e reqcond) {
        if (reqcond_apply == reqcond)    return "apply";
        if (reqcond_hit == reqcond)    return "hit";
        if (reqcond_miss == reqcond)    return "miss";
        if (reqcond_cond == reqcond)    return "cond";
        if (reqcond_run == reqcond)    return "run";
        if (reqcond_parse == reqcond)    return "parse";
        if (reqcond_NONE == reqcond)    return "NONE";
        if (reqcond_ERROR == reqcond)    return "ERROR";
        return "unreachable code";
    };
    
    
    #define MAX_PART_COUNT 128
    
    
    const char*const prefix_skip_char(const char*const txt, char c) {
        const char* ptr = txt;
        while (*ptr == c)  ++ptr;
        return ptr;
    }
    
    
    int split(char* parts[MAX_PART_COUNT], const char* reqs, const char* separator) {
        int count = 0;
        char* tmp = strdup(reqs);
        while ( (parts[count] = strsep(&tmp,separator)) != NULL )  ++count;
        free(tmp);
        return count;
    }
    
    
    bool check_table_name(const char*const table_name) {
        if (!strcmp("eth_dstMac_filter", table_name))    return true;
        if (!strcmp("eth_srcMac_filter", table_name))    return true;
        if (!strcmp("eth_proto_filter", table_name))    return true;
        if (!strcmp("ip_proto_filter", table_name))    return true;
        if (!strcmp("ip_dstIP_filter", table_name))    return true;
        if (!strcmp("ip_srcIP_filter", table_name))    return true;
        if (!strcmp("tcp_srcPort_filter", table_name))    return true;
        if (!strcmp("tcp_dstPort_filter", table_name))    return true;
        if (!strcmp("udp_srcPort_filter", table_name))    return true;
        if (!strcmp("udp_dstPort_filter", table_name))    return true;
        if (!strcmp("[ingress#1]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#1T]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#1F]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#2T]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#2F.if#1T]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#2F.if#1F]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#2F#2]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#3T]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#3F.if#1T]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#3F.if#1F]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#3F#2]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#4T]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#1T]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#1F]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#2T]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#2F.if#1T]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#2F.if#1F]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#2F#2]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#3T]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#3F.if#1T]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#3F.if#1F]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#3F#2]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#4T]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5T.if#1T]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5T.if#1F]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5T.if#2T]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5T.if#2F.if#1T]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5T.if#2F.if#1F]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5T.if#2F#2]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5T.if#3T]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5FT.if#1T]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5FT.if#1F]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5FT.if#2T.if#1T]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5FT.if#2T.if#1F]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5FT.if#2T#2]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5FT.if#2F]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5FT.if#3T]", table_name))    return true;
        if (!strcmp("[ingress.if#2T.if#6T]", table_name))    return true;
        return false;
    }
    
    
    bool check_table_requirement(const char*const table_name, reqcond_e reqcond, bool on) {
        t4p4s_stats_t stat = t4p4s_stats_per_packet;
        if (!strcmp("eth_dstMac_filter", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,eth_dstMac_filter_0)))   return true;
        if (!strcmp("eth_dstMac_filter", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,eth_dstMac_filter_0)))   return true;
        if (!strcmp("eth_dstMac_filter", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,eth_dstMac_filter_0)))   return true;
        if (!strcmp("eth_srcMac_filter", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,eth_srcMac_filter_0)))   return true;
        if (!strcmp("eth_srcMac_filter", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,eth_srcMac_filter_0)))   return true;
        if (!strcmp("eth_srcMac_filter", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,eth_srcMac_filter_0)))   return true;
        if (!strcmp("eth_proto_filter", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,eth_proto_filter_0)))   return true;
        if (!strcmp("eth_proto_filter", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,eth_proto_filter_0)))   return true;
        if (!strcmp("eth_proto_filter", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,eth_proto_filter_0)))   return true;
        if (!strcmp("ip_proto_filter", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,ip_proto_filter_0)))   return true;
        if (!strcmp("ip_proto_filter", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,ip_proto_filter_0)))   return true;
        if (!strcmp("ip_proto_filter", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,ip_proto_filter_0)))   return true;
        if (!strcmp("ip_dstIP_filter", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,ip_dstIP_filter_0)))   return true;
        if (!strcmp("ip_dstIP_filter", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,ip_dstIP_filter_0)))   return true;
        if (!strcmp("ip_dstIP_filter", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,ip_dstIP_filter_0)))   return true;
        if (!strcmp("ip_srcIP_filter", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,ip_srcIP_filter_0)))   return true;
        if (!strcmp("ip_srcIP_filter", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,ip_srcIP_filter_0)))   return true;
        if (!strcmp("ip_srcIP_filter", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,ip_srcIP_filter_0)))   return true;
        if (!strcmp("tcp_srcPort_filter", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tcp_srcPort_filter_0)))   return true;
        if (!strcmp("tcp_srcPort_filter", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tcp_srcPort_filter_0)))   return true;
        if (!strcmp("tcp_srcPort_filter", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tcp_srcPort_filter_0)))   return true;
        if (!strcmp("tcp_dstPort_filter", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tcp_dstPort_filter_0)))   return true;
        if (!strcmp("tcp_dstPort_filter", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tcp_dstPort_filter_0)))   return true;
        if (!strcmp("tcp_dstPort_filter", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tcp_dstPort_filter_0)))   return true;
        if (!strcmp("udp_srcPort_filter", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,udp_srcPort_filter_0)))   return true;
        if (!strcmp("udp_srcPort_filter", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,udp_srcPort_filter_0)))   return true;
        if (!strcmp("udp_srcPort_filter", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,udp_srcPort_filter_0)))   return true;
        if (!strcmp("udp_dstPort_filter", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,udp_dstPort_filter_0)))   return true;
        if (!strcmp("udp_dstPort_filter", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,udp_dstPort_filter_0)))   return true;
        if (!strcmp("udp_dstPort_filter", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,udp_dstPort_filter_0)))   return true;
        if (!strcmp("[ingress#1]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_firewall210)))   return true;
        if (!strcmp("[ingress#1]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_firewall210)))   return true;
        if (!strcmp("[ingress#1]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_firewall210)))   return true;
        if (!strcmp("[ingress.if#2T.if#1T]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_act)))   return true;
        if (!strcmp("[ingress.if#2T.if#1T]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_act)))   return true;
        if (!strcmp("[ingress.if#2T.if#1T]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_act)))   return true;
        if (!strcmp("[ingress.if#2T.if#1F]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_act_0)))   return true;
        if (!strcmp("[ingress.if#2T.if#1F]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_act_0)))   return true;
        if (!strcmp("[ingress.if#2T.if#1F]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_act_0)))   return true;
        if (!strcmp("[ingress.if#2T.if#2T]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_firewall212)))   return true;
        if (!strcmp("[ingress.if#2T.if#2T]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_firewall212)))   return true;
        if (!strcmp("[ingress.if#2T.if#2T]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_firewall212)))   return true;
        if (!strcmp("[ingress.if#2T.if#2F.if#1T]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_act_1)))   return true;
        if (!strcmp("[ingress.if#2T.if#2F.if#1T]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_act_1)))   return true;
        if (!strcmp("[ingress.if#2T.if#2F.if#1T]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_act_1)))   return true;
        if (!strcmp("[ingress.if#2T.if#2F.if#1F]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_act_2)))   return true;
        if (!strcmp("[ingress.if#2T.if#2F.if#1F]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_act_2)))   return true;
        if (!strcmp("[ingress.if#2T.if#2F.if#1F]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_act_2)))   return true;
        if (!strcmp("[ingress.if#2T.if#2F#2]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_firewall212_0)))   return true;
        if (!strcmp("[ingress.if#2T.if#2F#2]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_firewall212_0)))   return true;
        if (!strcmp("[ingress.if#2T.if#2F#2]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_firewall212_0)))   return true;
        if (!strcmp("[ingress.if#2T.if#3T]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_firewall212_1)))   return true;
        if (!strcmp("[ingress.if#2T.if#3T]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_firewall212_1)))   return true;
        if (!strcmp("[ingress.if#2T.if#3T]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_firewall212_1)))   return true;
        if (!strcmp("[ingress.if#2T.if#3F.if#1T]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_act_3)))   return true;
        if (!strcmp("[ingress.if#2T.if#3F.if#1T]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_act_3)))   return true;
        if (!strcmp("[ingress.if#2T.if#3F.if#1T]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_act_3)))   return true;
        if (!strcmp("[ingress.if#2T.if#3F.if#1F]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_act_4)))   return true;
        if (!strcmp("[ingress.if#2T.if#3F.if#1F]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_act_4)))   return true;
        if (!strcmp("[ingress.if#2T.if#3F.if#1F]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_act_4)))   return true;
        if (!strcmp("[ingress.if#2T.if#3F#2]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_firewall212_2)))   return true;
        if (!strcmp("[ingress.if#2T.if#3F#2]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_firewall212_2)))   return true;
        if (!strcmp("[ingress.if#2T.if#3F#2]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_firewall212_2)))   return true;
        if (!strcmp("[ingress.if#2T.if#4T]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_firewall213)))   return true;
        if (!strcmp("[ingress.if#2T.if#4T]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_firewall213)))   return true;
        if (!strcmp("[ingress.if#2T.if#4T]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_firewall213)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#1T]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_act_5)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#1T]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_act_5)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#1T]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_act_5)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#1F]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_act_6)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#1F]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_act_6)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#1F]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_act_6)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#2T]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_firewall215)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#2T]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_firewall215)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#2T]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_firewall215)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#2F.if#1T]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_act_7)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#2F.if#1T]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_act_7)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#2F.if#1T]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_act_7)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#2F.if#1F]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_act_8)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#2F.if#1F]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_act_8)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#2F.if#1F]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_act_8)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#2F#2]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_firewall215_0)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#2F#2]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_firewall215_0)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#2F#2]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_firewall215_0)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#3T]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_firewall215_1)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#3T]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_firewall215_1)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#3T]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_firewall215_1)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#3F.if#1T]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_act_9)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#3F.if#1T]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_act_9)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#3F.if#1T]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_act_9)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#3F.if#1F]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_act_10)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#3F.if#1F]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_act_10)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#3F.if#1F]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_act_10)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#3F#2]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_firewall215_2)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#3F#2]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_firewall215_2)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#3F#2]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_firewall215_2)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#4T]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_firewall216)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#4T]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_firewall216)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#4T]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_firewall216)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5T.if#1T]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_act_11)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5T.if#1T]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_act_11)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5T.if#1T]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_act_11)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5T.if#1F]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_act_12)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5T.if#1F]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_act_12)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5T.if#1F]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_act_12)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5T.if#2T]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_firewall218)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5T.if#2T]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_firewall218)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5T.if#2T]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_firewall218)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5T.if#2F.if#1T]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_act_13)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5T.if#2F.if#1T]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_act_13)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5T.if#2F.if#1T]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_act_13)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5T.if#2F.if#1F]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_act_14)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5T.if#2F.if#1F]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_act_14)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5T.if#2F.if#1F]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_act_14)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5T.if#2F#2]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_firewall218_0)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5T.if#2F#2]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_firewall218_0)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5T.if#2F#2]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_firewall218_0)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5T.if#3T]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_firewall219)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5T.if#3T]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_firewall219)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5T.if#3T]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_firewall219)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5FT.if#1T]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_act_15)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5FT.if#1T]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_act_15)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5FT.if#1T]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_act_15)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5FT.if#1F]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_act_16)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5FT.if#1F]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_act_16)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5FT.if#1F]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_act_16)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5FT.if#2T.if#1T]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_act_17)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5FT.if#2T.if#1T]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_act_17)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5FT.if#2T.if#1T]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_act_17)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5FT.if#2T.if#1F]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_act_18)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5FT.if#2T.if#1F]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_act_18)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5FT.if#2T.if#1F]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_act_18)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5FT.if#2T#2]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_firewall222)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5FT.if#2T#2]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_firewall222)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5FT.if#2T#2]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_firewall222)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5FT.if#2F]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_firewall222_0)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5FT.if#2F]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_firewall222_0)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5FT.if#2F]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_firewall222_0)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5FT.if#3T]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_firewall223)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5FT.if#3T]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_firewall223)))   return true;
        if (!strcmp("[ingress.if#2T.if#5T.if#5FT.if#3T]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_firewall223)))   return true;
        if (!strcmp("[ingress.if#2T.if#6T]", table_name) && reqcond == reqcond_apply && (on == stat.T4STAT(table,apply,tbl_firewall229)))   return true;
        if (!strcmp("[ingress.if#2T.if#6T]", table_name) && reqcond == reqcond_hit && (on == stat.T4STAT(table,hit,tbl_firewall229)))   return true;
        if (!strcmp("[ingress.if#2T.if#6T]", table_name) && reqcond == reqcond_miss && (on == stat.T4STAT(table,miss,tbl_firewall229)))   return true;
        return false;
    }
    
    
    bool check_action_requirement(const char*const table_name, reqcond_e reqcond, bool on) {
        return false;
    }
    
    
    bool check_parser_requirement(const char*const table_name, reqcond_e reqcond, bool on) {
        return false;
    }
    
    
    bool check_cond(const char*const cond) {
        const char*const ltrimmed_cond = prefix_skip_char(cond, ' ');
        bool on = true;
        
        bool result = true;
        reqcond_e reqcond = reqcond_NONE;
        char* parts[MAX_PART_COUNT];
        int part_count = split(parts, cond, " ");
        for (int i = 0; i < part_count; ++i) {
        if (strlen(parts[i]) == 0)    continue;
        if (!strcmp("apply", parts[i])) {
            if (reqcond != reqcond_NONE) {
                debug("    " T4LIT(!,warning) " More than one requirement (" T4LIT(apply,warning) " and " T4LIT(%s,warning) ") found in condition " T4LIT(%s,warning) "\n",
                parts[i], ltrimmed_cond);
                result = false;
                goto free_mem; // breaking out of outermost loop
            }
            reqcond = get_reqcond(parts[i]);
            continue;
        }
        if (!strcmp("hit", parts[i])) {
            if (reqcond != reqcond_NONE) {
                debug("    " T4LIT(!,warning) " More than one requirement (" T4LIT(hit,warning) " and " T4LIT(%s,warning) ") found in condition " T4LIT(%s,warning) "\n",
                parts[i], ltrimmed_cond);
                result = false;
                goto free_mem; // breaking out of outermost loop
            }
            reqcond = get_reqcond(parts[i]);
            continue;
        }
        if (!strcmp("miss", parts[i])) {
            if (reqcond != reqcond_NONE) {
                debug("    " T4LIT(!,warning) " More than one requirement (" T4LIT(miss,warning) " and " T4LIT(%s,warning) ") found in condition " T4LIT(%s,warning) "\n",
                parts[i], ltrimmed_cond);
                result = false;
                goto free_mem; // breaking out of outermost loop
            }
            reqcond = get_reqcond(parts[i]);
            continue;
        }
        if (!strcmp("cond", parts[i])) {
            if (reqcond != reqcond_NONE) {
                debug("    " T4LIT(!,warning) " More than one requirement (" T4LIT(cond,warning) " and " T4LIT(%s,warning) ") found in condition " T4LIT(%s,warning) "\n",
                parts[i], ltrimmed_cond);
                result = false;
                goto free_mem; // breaking out of outermost loop
            }
            reqcond = get_reqcond(parts[i]);
            continue;
        }
        if (!strcmp("run", parts[i])) {
            if (reqcond != reqcond_NONE) {
                debug("    " T4LIT(!,warning) " More than one requirement (" T4LIT(run,warning) " and " T4LIT(%s,warning) ") found in condition " T4LIT(%s,warning) "\n",
                parts[i], ltrimmed_cond);
                result = false;
                goto free_mem; // breaking out of outermost loop
            }
            reqcond = get_reqcond(parts[i]);
            continue;
        }
        if (!strcmp("parse", parts[i])) {
            if (reqcond != reqcond_NONE) {
                debug("    " T4LIT(!,warning) " More than one requirement (" T4LIT(parse,warning) " and " T4LIT(%s,warning) ") found in condition " T4LIT(%s,warning) "\n",
                parts[i], ltrimmed_cond);
                result = false;
                goto free_mem; // breaking out of outermost loop
            }
            reqcond = get_reqcond(parts[i]);
            continue;
        }
        if (!strcmp("NONE", parts[i])) {
            if (reqcond != reqcond_NONE) {
                debug("    " T4LIT(!,warning) " More than one requirement (" T4LIT(NONE,warning) " and " T4LIT(%s,warning) ") found in condition " T4LIT(%s,warning) "\n",
                parts[i], ltrimmed_cond);
                result = false;
                goto free_mem; // breaking out of outermost loop
            }
            reqcond = get_reqcond(parts[i]);
            continue;
        }
        if (!strcmp("ERROR", parts[i])) {
            if (reqcond != reqcond_NONE) {
                debug("    " T4LIT(!,warning) " More than one requirement (" T4LIT(ERROR,warning) " and " T4LIT(%s,warning) ") found in condition " T4LIT(%s,warning) "\n",
                parts[i], ltrimmed_cond);
                result = false;
                goto free_mem; // breaking out of outermost loop
            }
            reqcond = get_reqcond(parts[i]);
            continue;
        }
        if (!strcmp("not", parts[i])) {
            if (!on) {
                debug("    " T4LIT(!,warning) " Condition contains multiple negation: " T4LIT(%s,warning) "\n", ltrimmed_cond);
                result = false;
                goto free_mem; // breaking out of outermost loop
            }
            on = false;
            continue;
        }
        
        // we have found a table name
        
        if (reqcond == reqcond_NONE) {
            debug("    " T4LIT(!,warning) " Table " T4LIT(%s,table) " found, but no check (e.g. " T4LIT(hit) ") given in condition " T4LIT(%s,warning) "\n", parts[i], ltrimmed_cond);
            result = false;
            goto free_mem; // breaking out of outermost loop
        }
        
        result &= check_table_name(parts[i]);
        if (!result) {
            debug("    " T4LIT(!,warning) " Nonexistent table " T4LIT(%s,table) " given in condition " T4LIT(%s,warning) "\n", parts[i], ltrimmed_cond);
            result = false;
            goto free_mem; // breaking out of outermost loop
        }
        
        result &= check_table_requirement(parts[i], reqcond, on);
        if (!result) {
            debug("    " T4LIT(!,warning) " Requirement " T4LIT(%s%s) " on table " T4LIT(%s,table) " failed in condition " T4LIT(%s,warning) "\n",
            on ? "" : "not ", get_reqcond_txt(reqcond), parts[i], cond);
            result = false;
            goto free_mem; // breaking out of outermost loop
            } else {
            result = true;
            goto free_mem; // condition holds, breaking out of outermost loop
        }
        
        }
        
        debug("    " T4LIT(!,warning) " No table given in condition " T4LIT(%s,warning) "\n", cond);
        result = false;
        
        free_mem:
        free(parts[0]);
        return result;
    }
    
    
    bool check_controlflow_requirements(fake_cmd_t cmd) {
        bool result = true;
        const char* reqs = cmd.requirements[0];
        char* conds[MAX_PART_COUNT];
        int part_count = split(conds, reqs, ",");
        for (int i = 0; i < part_count; ++i) {
        result &= check_cond(conds[i]);
        }
        free(conds[0]);
        return result;
    }
    
    
#endif
