// Autogenerated file (from src/hardware_indep/stateful_memory.h.py: via hardware_indep/stateful_memory.h.py), do not modify directly.
// Generator: T4P4S (https://github.com/P4ELTE/t4p4s/)

#pragma once

#include "common.h"
#include "aliases.h"
#include "dpdk_smem.h"
#include "gen_include.h"
#include "stateful_memory_type.h"

typedef struct {
    
    
    
    
    
    
    uint8_t EXTERNNAME(dropped_0);
    bool EXTERNNAME(tmp);
    bool EXTERNNAME(tmp_0);
    bool EXTERNNAME(tmp_1);
    bool EXTERNNAME(tmp_2);
    bool EXTERNNAME(tmp_3);
    bool EXTERNNAME(tmp_4);
    bool EXTERNNAME(tmp_5);
    bool EXTERNNAME(tmp_6);
    bool EXTERNNAME(tmp_7);
    bool EXTERNNAME(tmp_8);
    bool EXTERNNAME(tmp_9);
    bool EXTERNNAME(tmp_10);
    bool EXTERNNAME(tmp_11);
    bool EXTERNNAME(tmp_12);
    bool EXTERNNAME(tmp_13);
    bool EXTERNNAME(tmp_14);
    uint8_t EXTERNNAME(rnd8_0);
    uint16_t EXTERNNAME(rnd16_0);
    uint32_t EXTERNNAME(rnd32_0);
    
} global_state_t;

extern global_state_t global_smem;

static lock_t ingress_lock;
static lock_t egress_lock;
