// Autogenerated file (from src/hardware_indep/stateful_memory.h.py: via hardware_indep/stateful_memory.h.py), do not modify directly.
// Generator: T4P4S (https://github.com/P4ELTE/t4p4s/)

#pragma once

#include "common.h"
#include "aliases.h"
#include "dpdk_smem.h"
#include "gen_include.h"
#include "stateful_memory_type.h"

typedef struct {
    
    
    
    
    uint32_t nhgroup_1;
    uint8_t* dmac_val;
    uint8_t* smac_val;
    uint16_t port;
    
    
    uint8_t EXTERNNAME(rnd8_0);
    uint16_t EXTERNNAME(rnd16_0);
    uint32_t EXTERNNAME(rnd32_0);
    
} global_state_t;

extern global_state_t global_smem;

static lock_t ingress_lock;
static lock_t egress_lock;
