// Autogenerated file (from src/hardware_indep/stats.h.py: via hardware_indep/stats.h.py), do not modify directly.
// Generator: T4P4S (https://github.com/P4ELTE/t4p4s/)

// SPDX-License-Identifier: Apache-2.0
// Copyright 2021 Eotvos Lorand University, Budapest, Hungary

#pragma once

#define T4STAT(part1, part2, part3)   t4stat_ ## part1 ## _ ## part2 ## _ ## part3
#define T4REQ(part1, part2, part3)   t4req_ ## part1 ## _ ## part2 ## _ ## part3

typedef enum {
    t4stat1_action,
    t4stat1_parser,
    t4stat1_table,
} t4p4s_stat1_e;

typedef enum {
    t4stat2_apply,
    t4stat2_eth_dstMac_filter_0,
    t4stat2_eth_proto_filter_0,
    t4stat2_eth_srcMac_filter_0,
    t4stat2_ip_dstIP_filter_0,
    t4stat2_ip_proto_filter_0,
    t4stat2_ip_srcIP_filter_0,
    t4stat2_state,
    t4stat2_tbl_act,
    t4stat2_tbl_act_0,
    t4stat2_tbl_act_1,
    t4stat2_tbl_act_10,
    t4stat2_tbl_act_11,
    t4stat2_tbl_act_12,
    t4stat2_tbl_act_13,
    t4stat2_tbl_act_14,
    t4stat2_tbl_act_15,
    t4stat2_tbl_act_16,
    t4stat2_tbl_act_17,
    t4stat2_tbl_act_18,
    t4stat2_tbl_act_2,
    t4stat2_tbl_act_3,
    t4stat2_tbl_act_4,
    t4stat2_tbl_act_5,
    t4stat2_tbl_act_6,
    t4stat2_tbl_act_7,
    t4stat2_tbl_act_8,
    t4stat2_tbl_act_9,
    t4stat2_tbl_firewall210,
    t4stat2_tbl_firewall212,
    t4stat2_tbl_firewall212_0,
    t4stat2_tbl_firewall212_1,
    t4stat2_tbl_firewall212_2,
    t4stat2_tbl_firewall213,
    t4stat2_tbl_firewall215,
    t4stat2_tbl_firewall215_0,
    t4stat2_tbl_firewall215_1,
    t4stat2_tbl_firewall215_2,
    t4stat2_tbl_firewall216,
    t4stat2_tbl_firewall218,
    t4stat2_tbl_firewall218_0,
    t4stat2_tbl_firewall219,
    t4stat2_tbl_firewall222,
    t4stat2_tbl_firewall222_0,
    t4stat2_tbl_firewall223,
    t4stat2_tbl_firewall229,
    t4stat2_tcp_dstPort_filter_0,
    t4stat2_tcp_srcPort_filter_0,
    t4stat2_udp_dstPort_filter_0,
    t4stat2_udp_srcPort_filter_0,
} t4p4s_stat2_e;

typedef enum {
    t4stat3_NoAction_1,
    t4stat3_NoAction_10,
    t4stat3_NoAction_2,
    t4stat3_NoAction_3,
    t4stat3_NoAction_4,
    t4stat3_NoAction_5,
    t4stat3_NoAction_6,
    t4stat3_NoAction_7,
    t4stat3_NoAction_8,
    t4stat3_NoAction_9,
    t4stat3_accept,
    t4stat3_act,
    t4stat3_act_0,
    t4stat3_act_1,
    t4stat3_act_10,
    t4stat3_act_11,
    t4stat3_act_12,
    t4stat3_act_13,
    t4stat3_act_14,
    t4stat3_act_15,
    t4stat3_act_16,
    t4stat3_act_17,
    t4stat3_act_18,
    t4stat3_act_2,
    t4stat3_act_3,
    t4stat3_act_4,
    t4stat3_act_5,
    t4stat3_act_6,
    t4stat3_act_7,
    t4stat3_act_8,
    t4stat3_act_9,
    t4stat3_drop,
    t4stat3_drop_1,
    t4stat3_drop_2,
    t4stat3_drop_3,
    t4stat3_drop_4,
    t4stat3_drop_5,
    t4stat3_drop_6,
    t4stat3_drop_7,
    t4stat3_drop_8,
    t4stat3_drop_9,
    t4stat3_eth_dstMac_filter_0,
    t4stat3_eth_proto_filter_0,
    t4stat3_eth_srcMac_filter_0,
    t4stat3_firewall210,
    t4stat3_firewall212,
    t4stat3_firewall212_0,
    t4stat3_firewall212_1,
    t4stat3_firewall212_2,
    t4stat3_firewall213,
    t4stat3_firewall215,
    t4stat3_firewall215_0,
    t4stat3_firewall215_1,
    t4stat3_firewall215_2,
    t4stat3_firewall216,
    t4stat3_firewall218,
    t4stat3_firewall218_0,
    t4stat3_firewall219,
    t4stat3_firewall222,
    t4stat3_firewall222_0,
    t4stat3_firewall223,
    t4stat3_firewall229,
    t4stat3_ip_dstIP_filter_0,
    t4stat3_ip_proto_filter_0,
    t4stat3_ip_srcIP_filter_0,
    t4stat3_parse_arp,
    t4stat3_parse_icmp,
    t4stat3_parse_ipv4,
    t4stat3_parse_tcp,
    t4stat3_parse_udp,
    t4stat3_reject,
    t4stat3_start,
    t4stat3_tbl_act,
    t4stat3_tbl_act_0,
    t4stat3_tbl_act_1,
    t4stat3_tbl_act_10,
    t4stat3_tbl_act_11,
    t4stat3_tbl_act_12,
    t4stat3_tbl_act_13,
    t4stat3_tbl_act_14,
    t4stat3_tbl_act_15,
    t4stat3_tbl_act_16,
    t4stat3_tbl_act_17,
    t4stat3_tbl_act_18,
    t4stat3_tbl_act_2,
    t4stat3_tbl_act_3,
    t4stat3_tbl_act_4,
    t4stat3_tbl_act_5,
    t4stat3_tbl_act_6,
    t4stat3_tbl_act_7,
    t4stat3_tbl_act_8,
    t4stat3_tbl_act_9,
    t4stat3_tbl_firewall210,
    t4stat3_tbl_firewall212,
    t4stat3_tbl_firewall212_0,
    t4stat3_tbl_firewall212_1,
    t4stat3_tbl_firewall212_2,
    t4stat3_tbl_firewall213,
    t4stat3_tbl_firewall215,
    t4stat3_tbl_firewall215_0,
    t4stat3_tbl_firewall215_1,
    t4stat3_tbl_firewall215_2,
    t4stat3_tbl_firewall216,
    t4stat3_tbl_firewall218,
    t4stat3_tbl_firewall218_0,
    t4stat3_tbl_firewall219,
    t4stat3_tbl_firewall222,
    t4stat3_tbl_firewall222_0,
    t4stat3_tbl_firewall223,
    t4stat3_tbl_firewall229,
    t4stat3_tcp_dstPort_filter_0,
    t4stat3_tcp_srcPort_filter_0,
    t4stat3_udp_dstPort_filter_0,
    t4stat3_udp_srcPort_filter_0,
} t4p4s_stat3_e;

typedef struct {
    bool T4STAT(parser,state,parse_arp);
    bool T4STAT(parser,state,parse_icmp);
    bool T4STAT(parser,state,parse_tcp);
    bool T4STAT(parser,state,parse_udp);
    bool T4STAT(parser,state,parse_ipv4);
    bool T4STAT(parser,state,start);
    bool T4STAT(parser,state,accept);
    bool T4STAT(parser,state,reject);
    
    
    bool T4STAT(table,apply,eth_dstMac_filter_0);
    bool T4STAT(table,hit,eth_dstMac_filter_0);
    bool T4STAT(table,miss,eth_dstMac_filter_0);
    bool T4STAT(action,eth_dstMac_filter_0,drop);
    bool T4STAT(action,eth_dstMac_filter_0,NoAction_1);
    bool T4STAT(table,apply,eth_srcMac_filter_0);
    bool T4STAT(table,hit,eth_srcMac_filter_0);
    bool T4STAT(table,miss,eth_srcMac_filter_0);
    bool T4STAT(action,eth_srcMac_filter_0,drop_1);
    bool T4STAT(action,eth_srcMac_filter_0,NoAction_2);
    bool T4STAT(table,apply,eth_proto_filter_0);
    bool T4STAT(table,hit,eth_proto_filter_0);
    bool T4STAT(table,miss,eth_proto_filter_0);
    bool T4STAT(action,eth_proto_filter_0,drop_2);
    bool T4STAT(action,eth_proto_filter_0,NoAction_3);
    bool T4STAT(table,apply,ip_proto_filter_0);
    bool T4STAT(table,hit,ip_proto_filter_0);
    bool T4STAT(table,miss,ip_proto_filter_0);
    bool T4STAT(action,ip_proto_filter_0,drop_3);
    bool T4STAT(action,ip_proto_filter_0,NoAction_4);
    bool T4STAT(table,apply,ip_dstIP_filter_0);
    bool T4STAT(table,hit,ip_dstIP_filter_0);
    bool T4STAT(table,miss,ip_dstIP_filter_0);
    bool T4STAT(action,ip_dstIP_filter_0,drop_4);
    bool T4STAT(action,ip_dstIP_filter_0,NoAction_5);
    bool T4STAT(table,apply,ip_srcIP_filter_0);
    bool T4STAT(table,hit,ip_srcIP_filter_0);
    bool T4STAT(table,miss,ip_srcIP_filter_0);
    bool T4STAT(action,ip_srcIP_filter_0,drop_5);
    bool T4STAT(action,ip_srcIP_filter_0,NoAction_6);
    bool T4STAT(table,apply,tcp_srcPort_filter_0);
    bool T4STAT(table,hit,tcp_srcPort_filter_0);
    bool T4STAT(table,miss,tcp_srcPort_filter_0);
    bool T4STAT(action,tcp_srcPort_filter_0,drop_6);
    bool T4STAT(action,tcp_srcPort_filter_0,NoAction_7);
    bool T4STAT(table,apply,tcp_dstPort_filter_0);
    bool T4STAT(table,hit,tcp_dstPort_filter_0);
    bool T4STAT(table,miss,tcp_dstPort_filter_0);
    bool T4STAT(action,tcp_dstPort_filter_0,drop_7);
    bool T4STAT(action,tcp_dstPort_filter_0,NoAction_8);
    bool T4STAT(table,apply,udp_srcPort_filter_0);
    bool T4STAT(table,hit,udp_srcPort_filter_0);
    bool T4STAT(table,miss,udp_srcPort_filter_0);
    bool T4STAT(action,udp_srcPort_filter_0,drop_8);
    bool T4STAT(action,udp_srcPort_filter_0,NoAction_9);
    bool T4STAT(table,apply,udp_dstPort_filter_0);
    bool T4STAT(table,hit,udp_dstPort_filter_0);
    bool T4STAT(table,miss,udp_dstPort_filter_0);
    bool T4STAT(action,udp_dstPort_filter_0,drop_9);
    bool T4STAT(action,udp_dstPort_filter_0,NoAction_10);
    bool T4STAT(table,apply,tbl_firewall210);
    bool T4STAT(table,hit,tbl_firewall210);
    bool T4STAT(table,miss,tbl_firewall210);
    bool T4STAT(action,tbl_firewall210,firewall210);
    bool T4STAT(table,apply,tbl_act);
    bool T4STAT(table,hit,tbl_act);
    bool T4STAT(table,miss,tbl_act);
    bool T4STAT(action,tbl_act,act);
    bool T4STAT(table,apply,tbl_act_0);
    bool T4STAT(table,hit,tbl_act_0);
    bool T4STAT(table,miss,tbl_act_0);
    bool T4STAT(action,tbl_act_0,act_0);
    bool T4STAT(table,apply,tbl_firewall212);
    bool T4STAT(table,hit,tbl_firewall212);
    bool T4STAT(table,miss,tbl_firewall212);
    bool T4STAT(action,tbl_firewall212,firewall212);
    bool T4STAT(table,apply,tbl_act_1);
    bool T4STAT(table,hit,tbl_act_1);
    bool T4STAT(table,miss,tbl_act_1);
    bool T4STAT(action,tbl_act_1,act_1);
    bool T4STAT(table,apply,tbl_act_2);
    bool T4STAT(table,hit,tbl_act_2);
    bool T4STAT(table,miss,tbl_act_2);
    bool T4STAT(action,tbl_act_2,act_2);
    bool T4STAT(table,apply,tbl_firewall212_0);
    bool T4STAT(table,hit,tbl_firewall212_0);
    bool T4STAT(table,miss,tbl_firewall212_0);
    bool T4STAT(action,tbl_firewall212_0,firewall212_0);
    bool T4STAT(table,apply,tbl_firewall212_1);
    bool T4STAT(table,hit,tbl_firewall212_1);
    bool T4STAT(table,miss,tbl_firewall212_1);
    bool T4STAT(action,tbl_firewall212_1,firewall212_1);
    bool T4STAT(table,apply,tbl_act_3);
    bool T4STAT(table,hit,tbl_act_3);
    bool T4STAT(table,miss,tbl_act_3);
    bool T4STAT(action,tbl_act_3,act_3);
    bool T4STAT(table,apply,tbl_act_4);
    bool T4STAT(table,hit,tbl_act_4);
    bool T4STAT(table,miss,tbl_act_4);
    bool T4STAT(action,tbl_act_4,act_4);
    bool T4STAT(table,apply,tbl_firewall212_2);
    bool T4STAT(table,hit,tbl_firewall212_2);
    bool T4STAT(table,miss,tbl_firewall212_2);
    bool T4STAT(action,tbl_firewall212_2,firewall212_2);
    bool T4STAT(table,apply,tbl_firewall213);
    bool T4STAT(table,hit,tbl_firewall213);
    bool T4STAT(table,miss,tbl_firewall213);
    bool T4STAT(action,tbl_firewall213,firewall213);
    bool T4STAT(table,apply,tbl_act_5);
    bool T4STAT(table,hit,tbl_act_5);
    bool T4STAT(table,miss,tbl_act_5);
    bool T4STAT(action,tbl_act_5,act_5);
    bool T4STAT(table,apply,tbl_act_6);
    bool T4STAT(table,hit,tbl_act_6);
    bool T4STAT(table,miss,tbl_act_6);
    bool T4STAT(action,tbl_act_6,act_6);
    bool T4STAT(table,apply,tbl_firewall215);
    bool T4STAT(table,hit,tbl_firewall215);
    bool T4STAT(table,miss,tbl_firewall215);
    bool T4STAT(action,tbl_firewall215,firewall215);
    bool T4STAT(table,apply,tbl_act_7);
    bool T4STAT(table,hit,tbl_act_7);
    bool T4STAT(table,miss,tbl_act_7);
    bool T4STAT(action,tbl_act_7,act_7);
    bool T4STAT(table,apply,tbl_act_8);
    bool T4STAT(table,hit,tbl_act_8);
    bool T4STAT(table,miss,tbl_act_8);
    bool T4STAT(action,tbl_act_8,act_8);
    bool T4STAT(table,apply,tbl_firewall215_0);
    bool T4STAT(table,hit,tbl_firewall215_0);
    bool T4STAT(table,miss,tbl_firewall215_0);
    bool T4STAT(action,tbl_firewall215_0,firewall215_0);
    bool T4STAT(table,apply,tbl_firewall215_1);
    bool T4STAT(table,hit,tbl_firewall215_1);
    bool T4STAT(table,miss,tbl_firewall215_1);
    bool T4STAT(action,tbl_firewall215_1,firewall215_1);
    bool T4STAT(table,apply,tbl_act_9);
    bool T4STAT(table,hit,tbl_act_9);
    bool T4STAT(table,miss,tbl_act_9);
    bool T4STAT(action,tbl_act_9,act_9);
    bool T4STAT(table,apply,tbl_act_10);
    bool T4STAT(table,hit,tbl_act_10);
    bool T4STAT(table,miss,tbl_act_10);
    bool T4STAT(action,tbl_act_10,act_10);
    bool T4STAT(table,apply,tbl_firewall215_2);
    bool T4STAT(table,hit,tbl_firewall215_2);
    bool T4STAT(table,miss,tbl_firewall215_2);
    bool T4STAT(action,tbl_firewall215_2,firewall215_2);
    bool T4STAT(table,apply,tbl_firewall216);
    bool T4STAT(table,hit,tbl_firewall216);
    bool T4STAT(table,miss,tbl_firewall216);
    bool T4STAT(action,tbl_firewall216,firewall216);
    bool T4STAT(table,apply,tbl_act_11);
    bool T4STAT(table,hit,tbl_act_11);
    bool T4STAT(table,miss,tbl_act_11);
    bool T4STAT(action,tbl_act_11,act_11);
    bool T4STAT(table,apply,tbl_act_12);
    bool T4STAT(table,hit,tbl_act_12);
    bool T4STAT(table,miss,tbl_act_12);
    bool T4STAT(action,tbl_act_12,act_12);
    bool T4STAT(table,apply,tbl_firewall218);
    bool T4STAT(table,hit,tbl_firewall218);
    bool T4STAT(table,miss,tbl_firewall218);
    bool T4STAT(action,tbl_firewall218,firewall218);
    bool T4STAT(table,apply,tbl_act_13);
    bool T4STAT(table,hit,tbl_act_13);
    bool T4STAT(table,miss,tbl_act_13);
    bool T4STAT(action,tbl_act_13,act_13);
    bool T4STAT(table,apply,tbl_act_14);
    bool T4STAT(table,hit,tbl_act_14);
    bool T4STAT(table,miss,tbl_act_14);
    bool T4STAT(action,tbl_act_14,act_14);
    bool T4STAT(table,apply,tbl_firewall218_0);
    bool T4STAT(table,hit,tbl_firewall218_0);
    bool T4STAT(table,miss,tbl_firewall218_0);
    bool T4STAT(action,tbl_firewall218_0,firewall218_0);
    bool T4STAT(table,apply,tbl_firewall219);
    bool T4STAT(table,hit,tbl_firewall219);
    bool T4STAT(table,miss,tbl_firewall219);
    bool T4STAT(action,tbl_firewall219,firewall219);
    bool T4STAT(table,apply,tbl_act_15);
    bool T4STAT(table,hit,tbl_act_15);
    bool T4STAT(table,miss,tbl_act_15);
    bool T4STAT(action,tbl_act_15,act_15);
    bool T4STAT(table,apply,tbl_act_16);
    bool T4STAT(table,hit,tbl_act_16);
    bool T4STAT(table,miss,tbl_act_16);
    bool T4STAT(action,tbl_act_16,act_16);
    bool T4STAT(table,apply,tbl_act_17);
    bool T4STAT(table,hit,tbl_act_17);
    bool T4STAT(table,miss,tbl_act_17);
    bool T4STAT(action,tbl_act_17,act_17);
    bool T4STAT(table,apply,tbl_act_18);
    bool T4STAT(table,hit,tbl_act_18);
    bool T4STAT(table,miss,tbl_act_18);
    bool T4STAT(action,tbl_act_18,act_18);
    bool T4STAT(table,apply,tbl_firewall222);
    bool T4STAT(table,hit,tbl_firewall222);
    bool T4STAT(table,miss,tbl_firewall222);
    bool T4STAT(action,tbl_firewall222,firewall222);
    bool T4STAT(table,apply,tbl_firewall222_0);
    bool T4STAT(table,hit,tbl_firewall222_0);
    bool T4STAT(table,miss,tbl_firewall222_0);
    bool T4STAT(action,tbl_firewall222_0,firewall222_0);
    bool T4STAT(table,apply,tbl_firewall223);
    bool T4STAT(table,hit,tbl_firewall223);
    bool T4STAT(table,miss,tbl_firewall223);
    bool T4STAT(action,tbl_firewall223,firewall223);
    bool T4STAT(table,apply,tbl_firewall229);
    bool T4STAT(table,hit,tbl_firewall229);
    bool T4STAT(table,miss,tbl_firewall229);
    bool T4STAT(action,tbl_firewall229,firewall229);
} t4p4s_stats_t;

typedef enum {
    req_none,
    T4REQ(parser,state,parse_arp),
    T4REQ(parser,state,parse_icmp),
    T4REQ(parser,state,parse_tcp),
    T4REQ(parser,state,parse_udp),
    T4REQ(parser,state,parse_ipv4),
    T4REQ(parser,state,start),
    T4REQ(parser,state,accept),
    T4REQ(parser,state,reject),
    
    
    T4REQ(table,apply,eth_dstMac_filter_0),
    T4REQ(table,hit,eth_dstMac_filter_0),
    T4REQ(table,miss,eth_dstMac_filter_0),
    T4REQ(action,eth_dstMac_filter_0,drop),
    T4REQ(action,eth_dstMac_filter_0,NoAction_1),
    T4REQ(table,apply,eth_srcMac_filter_0),
    T4REQ(table,hit,eth_srcMac_filter_0),
    T4REQ(table,miss,eth_srcMac_filter_0),
    T4REQ(action,eth_srcMac_filter_0,drop_1),
    T4REQ(action,eth_srcMac_filter_0,NoAction_2),
    T4REQ(table,apply,eth_proto_filter_0),
    T4REQ(table,hit,eth_proto_filter_0),
    T4REQ(table,miss,eth_proto_filter_0),
    T4REQ(action,eth_proto_filter_0,drop_2),
    T4REQ(action,eth_proto_filter_0,NoAction_3),
    T4REQ(table,apply,ip_proto_filter_0),
    T4REQ(table,hit,ip_proto_filter_0),
    T4REQ(table,miss,ip_proto_filter_0),
    T4REQ(action,ip_proto_filter_0,drop_3),
    T4REQ(action,ip_proto_filter_0,NoAction_4),
    T4REQ(table,apply,ip_dstIP_filter_0),
    T4REQ(table,hit,ip_dstIP_filter_0),
    T4REQ(table,miss,ip_dstIP_filter_0),
    T4REQ(action,ip_dstIP_filter_0,drop_4),
    T4REQ(action,ip_dstIP_filter_0,NoAction_5),
    T4REQ(table,apply,ip_srcIP_filter_0),
    T4REQ(table,hit,ip_srcIP_filter_0),
    T4REQ(table,miss,ip_srcIP_filter_0),
    T4REQ(action,ip_srcIP_filter_0,drop_5),
    T4REQ(action,ip_srcIP_filter_0,NoAction_6),
    T4REQ(table,apply,tcp_srcPort_filter_0),
    T4REQ(table,hit,tcp_srcPort_filter_0),
    T4REQ(table,miss,tcp_srcPort_filter_0),
    T4REQ(action,tcp_srcPort_filter_0,drop_6),
    T4REQ(action,tcp_srcPort_filter_0,NoAction_7),
    T4REQ(table,apply,tcp_dstPort_filter_0),
    T4REQ(table,hit,tcp_dstPort_filter_0),
    T4REQ(table,miss,tcp_dstPort_filter_0),
    T4REQ(action,tcp_dstPort_filter_0,drop_7),
    T4REQ(action,tcp_dstPort_filter_0,NoAction_8),
    T4REQ(table,apply,udp_srcPort_filter_0),
    T4REQ(table,hit,udp_srcPort_filter_0),
    T4REQ(table,miss,udp_srcPort_filter_0),
    T4REQ(action,udp_srcPort_filter_0,drop_8),
    T4REQ(action,udp_srcPort_filter_0,NoAction_9),
    T4REQ(table,apply,udp_dstPort_filter_0),
    T4REQ(table,hit,udp_dstPort_filter_0),
    T4REQ(table,miss,udp_dstPort_filter_0),
    T4REQ(action,udp_dstPort_filter_0,drop_9),
    T4REQ(action,udp_dstPort_filter_0,NoAction_10),
    T4REQ(table,apply,tbl_firewall210),
    T4REQ(table,hit,tbl_firewall210),
    T4REQ(table,miss,tbl_firewall210),
    T4REQ(action,tbl_firewall210,firewall210),
    T4REQ(table,apply,tbl_act),
    T4REQ(table,hit,tbl_act),
    T4REQ(table,miss,tbl_act),
    T4REQ(action,tbl_act,act),
    T4REQ(table,apply,tbl_act_0),
    T4REQ(table,hit,tbl_act_0),
    T4REQ(table,miss,tbl_act_0),
    T4REQ(action,tbl_act_0,act_0),
    T4REQ(table,apply,tbl_firewall212),
    T4REQ(table,hit,tbl_firewall212),
    T4REQ(table,miss,tbl_firewall212),
    T4REQ(action,tbl_firewall212,firewall212),
    T4REQ(table,apply,tbl_act_1),
    T4REQ(table,hit,tbl_act_1),
    T4REQ(table,miss,tbl_act_1),
    T4REQ(action,tbl_act_1,act_1),
    T4REQ(table,apply,tbl_act_2),
    T4REQ(table,hit,tbl_act_2),
    T4REQ(table,miss,tbl_act_2),
    T4REQ(action,tbl_act_2,act_2),
    T4REQ(table,apply,tbl_firewall212_0),
    T4REQ(table,hit,tbl_firewall212_0),
    T4REQ(table,miss,tbl_firewall212_0),
    T4REQ(action,tbl_firewall212_0,firewall212_0),
    T4REQ(table,apply,tbl_firewall212_1),
    T4REQ(table,hit,tbl_firewall212_1),
    T4REQ(table,miss,tbl_firewall212_1),
    T4REQ(action,tbl_firewall212_1,firewall212_1),
    T4REQ(table,apply,tbl_act_3),
    T4REQ(table,hit,tbl_act_3),
    T4REQ(table,miss,tbl_act_3),
    T4REQ(action,tbl_act_3,act_3),
    T4REQ(table,apply,tbl_act_4),
    T4REQ(table,hit,tbl_act_4),
    T4REQ(table,miss,tbl_act_4),
    T4REQ(action,tbl_act_4,act_4),
    T4REQ(table,apply,tbl_firewall212_2),
    T4REQ(table,hit,tbl_firewall212_2),
    T4REQ(table,miss,tbl_firewall212_2),
    T4REQ(action,tbl_firewall212_2,firewall212_2),
    T4REQ(table,apply,tbl_firewall213),
    T4REQ(table,hit,tbl_firewall213),
    T4REQ(table,miss,tbl_firewall213),
    T4REQ(action,tbl_firewall213,firewall213),
    T4REQ(table,apply,tbl_act_5),
    T4REQ(table,hit,tbl_act_5),
    T4REQ(table,miss,tbl_act_5),
    T4REQ(action,tbl_act_5,act_5),
    T4REQ(table,apply,tbl_act_6),
    T4REQ(table,hit,tbl_act_6),
    T4REQ(table,miss,tbl_act_6),
    T4REQ(action,tbl_act_6,act_6),
    T4REQ(table,apply,tbl_firewall215),
    T4REQ(table,hit,tbl_firewall215),
    T4REQ(table,miss,tbl_firewall215),
    T4REQ(action,tbl_firewall215,firewall215),
    T4REQ(table,apply,tbl_act_7),
    T4REQ(table,hit,tbl_act_7),
    T4REQ(table,miss,tbl_act_7),
    T4REQ(action,tbl_act_7,act_7),
    T4REQ(table,apply,tbl_act_8),
    T4REQ(table,hit,tbl_act_8),
    T4REQ(table,miss,tbl_act_8),
    T4REQ(action,tbl_act_8,act_8),
    T4REQ(table,apply,tbl_firewall215_0),
    T4REQ(table,hit,tbl_firewall215_0),
    T4REQ(table,miss,tbl_firewall215_0),
    T4REQ(action,tbl_firewall215_0,firewall215_0),
    T4REQ(table,apply,tbl_firewall215_1),
    T4REQ(table,hit,tbl_firewall215_1),
    T4REQ(table,miss,tbl_firewall215_1),
    T4REQ(action,tbl_firewall215_1,firewall215_1),
    T4REQ(table,apply,tbl_act_9),
    T4REQ(table,hit,tbl_act_9),
    T4REQ(table,miss,tbl_act_9),
    T4REQ(action,tbl_act_9,act_9),
    T4REQ(table,apply,tbl_act_10),
    T4REQ(table,hit,tbl_act_10),
    T4REQ(table,miss,tbl_act_10),
    T4REQ(action,tbl_act_10,act_10),
    T4REQ(table,apply,tbl_firewall215_2),
    T4REQ(table,hit,tbl_firewall215_2),
    T4REQ(table,miss,tbl_firewall215_2),
    T4REQ(action,tbl_firewall215_2,firewall215_2),
    T4REQ(table,apply,tbl_firewall216),
    T4REQ(table,hit,tbl_firewall216),
    T4REQ(table,miss,tbl_firewall216),
    T4REQ(action,tbl_firewall216,firewall216),
    T4REQ(table,apply,tbl_act_11),
    T4REQ(table,hit,tbl_act_11),
    T4REQ(table,miss,tbl_act_11),
    T4REQ(action,tbl_act_11,act_11),
    T4REQ(table,apply,tbl_act_12),
    T4REQ(table,hit,tbl_act_12),
    T4REQ(table,miss,tbl_act_12),
    T4REQ(action,tbl_act_12,act_12),
    T4REQ(table,apply,tbl_firewall218),
    T4REQ(table,hit,tbl_firewall218),
    T4REQ(table,miss,tbl_firewall218),
    T4REQ(action,tbl_firewall218,firewall218),
    T4REQ(table,apply,tbl_act_13),
    T4REQ(table,hit,tbl_act_13),
    T4REQ(table,miss,tbl_act_13),
    T4REQ(action,tbl_act_13,act_13),
    T4REQ(table,apply,tbl_act_14),
    T4REQ(table,hit,tbl_act_14),
    T4REQ(table,miss,tbl_act_14),
    T4REQ(action,tbl_act_14,act_14),
    T4REQ(table,apply,tbl_firewall218_0),
    T4REQ(table,hit,tbl_firewall218_0),
    T4REQ(table,miss,tbl_firewall218_0),
    T4REQ(action,tbl_firewall218_0,firewall218_0),
    T4REQ(table,apply,tbl_firewall219),
    T4REQ(table,hit,tbl_firewall219),
    T4REQ(table,miss,tbl_firewall219),
    T4REQ(action,tbl_firewall219,firewall219),
    T4REQ(table,apply,tbl_act_15),
    T4REQ(table,hit,tbl_act_15),
    T4REQ(table,miss,tbl_act_15),
    T4REQ(action,tbl_act_15,act_15),
    T4REQ(table,apply,tbl_act_16),
    T4REQ(table,hit,tbl_act_16),
    T4REQ(table,miss,tbl_act_16),
    T4REQ(action,tbl_act_16,act_16),
    T4REQ(table,apply,tbl_act_17),
    T4REQ(table,hit,tbl_act_17),
    T4REQ(table,miss,tbl_act_17),
    T4REQ(action,tbl_act_17,act_17),
    T4REQ(table,apply,tbl_act_18),
    T4REQ(table,hit,tbl_act_18),
    T4REQ(table,miss,tbl_act_18),
    T4REQ(action,tbl_act_18,act_18),
    T4REQ(table,apply,tbl_firewall222),
    T4REQ(table,hit,tbl_firewall222),
    T4REQ(table,miss,tbl_firewall222),
    T4REQ(action,tbl_firewall222,firewall222),
    T4REQ(table,apply,tbl_firewall222_0),
    T4REQ(table,hit,tbl_firewall222_0),
    T4REQ(table,miss,tbl_firewall222_0),
    T4REQ(action,tbl_firewall222_0,firewall222_0),
    T4REQ(table,apply,tbl_firewall223),
    T4REQ(table,hit,tbl_firewall223),
    T4REQ(table,miss,tbl_firewall223),
    T4REQ(action,tbl_firewall223,firewall223),
    T4REQ(table,apply,tbl_firewall229),
    T4REQ(table,hit,tbl_firewall229),
    T4REQ(table,miss,tbl_firewall229),
    T4REQ(action,tbl_firewall229,firewall229),
} t4p4s_controlflow_name_e;

