// Autogenerated file (from src/hardware_indep/multi/actions.stage.c.py: via hardware_indep/multi/actions.stage.c.py), do not modify directly.
// Generator: T4P4S (https://github.com/P4ELTE/t4p4s/)

#define T4P4S_MULTI_IDX 1
#include "multi_actions.c"
