// Autogenerated file (from src/hardware_indep/multi/dataplane.stage.c.py: via hardware_indep/multi/dataplane.stage.c.py), do not modify directly.
// Generator: T4P4S (https://github.com/P4ELTE/t4p4s/)

#define T4P4S_MULTI_IDX 0
#include "multi_dataplane.c"
